#!/usr/bin/env node
/**
 * Build the Rust core to WebAssembly and wire it into the extension:
 *
 *   1. `wasm-pack build core --target web` → src/wasm/pkg/
 *      (JS glue + .wasm; the glue is bundled by WXT/Vite)
 *   2. The .wasm binary is base64-encoded into src/wasm/core-bytes.ts so
 *      the service worker can instantiate it from bytes via
 *      chrome-independent means — no runtime fetch of a packaged file,
 *      no CSP surprises, and instantiation stays fully async.
 *
 * Requires: cargo + the wasm32-unknown-unknown target, and wasm-pack.
 * Run with: npm run build:wasm
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkgDir = join(root, 'src', 'wasm', 'pkg');

execFileSync(
  'wasm-pack',
  ['build', join(root, 'core'), '--target', 'web', '--out-dir', pkgDir],
  { stdio: 'inherit' },
);

// wasm-pack's own wasm-opt download is disabled in core/Cargo.toml (it is
// unreliable in some environments); run a locally installed wasm-opt when
// one is available, and carry on unoptimized when it is not.
const wasmPath = join(pkgDir, 'tabsense_core_bg.wasm');
try {
  execFileSync('wasm-opt', ['-Oz', wasmPath, '-o', wasmPath], { stdio: 'inherit' });
  console.log('wasm-opt: optimized', wasmPath);
} catch {
  console.warn('wasm-opt not available — shipping unoptimized Wasm.');
}

const wasmBytes = readFileSync(wasmPath);
const b64 = wasmBytes.toString('base64');
writeFileSync(
  join(root, 'src', 'wasm', 'core-bytes.ts'),
  `// GENERATED by scripts/build-wasm.mjs — do not edit by hand.\n` +
    `// Base64 of src/wasm/pkg/tabsense_core_bg.wasm (${wasmBytes.length} bytes).\n` +
    `export const CORE_WASM_BASE64 =\n  '${b64}';\n`,
);
console.log(`Wrote src/wasm/core-bytes.ts (${wasmBytes.length} wasm bytes).`);
